#!/bin/bash

# Needs Debian packages: docbook-xml docbook-xsl gettext itstool xsltproc

cd `dirname "$0"`
if test $# -eq 0 ; then
    languages="C de"
else
    languages="$@"
fi
for lang in $languages; do
  case "$lang" in
  C)
    xsltproc --nonet \
      --path /usr/share/xml/docbook/stylesheet/docbook-xsl/html \
      -o ../help/C/pentobi/ custom.xsl index.docbook
    ;;
  *)
    msgfmt -o $lang.mo po/$lang.po
    itstool -m $lang.mo -o index_$lang.docbook index.docbook
    xsltproc --nonet \
      --path "/usr/share/xml/docbook/stylesheet/docbook-xsl/html" \
      --stringparam l10n.gentext.language $lang \
      -o ../help/$lang/pentobi/ custom.xsl index_$lang.docbook
    rm -f $lang.mo index_$lang.docbook
    ;;
  esac
done
