#!/bin/bash

# Needs Debian package gettext

if test $# -eq 0 ; then
    languages="de nb_NO"
else
    languages="$@"
fi
cd `dirname "$0"`
for lang in $languages; do
  msgmerge --update --backup=none po/$lang.po pentobi-manual.pot
done
