#!/bin/bash

cd `dirname "$0"`
xgettext -o pentobi-unix.pot \
  io.sourceforge.pentobi.appdata.xml \
  io.sourceforge.pentobi.desktop.in
# gettext 0.19 does not come with ITS rules for shared mime info
xgettext -j -o pentobi-unix.pot --its=mime.its pentobi-mime.xml.in
