#!/bin/bash

cd $(dirname "$0")
xgettext -o pentobi-unix.pot --add-location=file --add-comments="TRANSLATORS:" \
  io.sourceforge.pentobi.appdata.xml.in io.sourceforge.pentobi.desktop.in \
  io.sourceforge.pentobi.xml.in
